//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_podejscie_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ubrania3
    {
        public int Id { get; set; }
        public string TYP { get; set; }
        public string KOLOR { get; set; }
        public string ROZMIAR { get; set; }
        public string MARKA { get; set; }
        public string OPIS { get; set; }
        public Nullable<int> CENA { get; set; }
        public Nullable<int> CENA_RZ { get; set; }
        public string NR_SERYJNY { get; set; }
    }
}
